pipeline {
    agent any 

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout App') {
            steps {
                git url: 'https://github.com/vpolisetty-DevOps/Jenkins-Zero-to-Hero',
                branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                sh '''
                echo "Building Docker Image"
                docker build -t abhishekf5/cicd-e2e:${BUILD_NUMBER} .
                '''
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push abhishekf5/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Checkout Manifests') {
            steps {
                git url: 'https://github.com/iam-veeramalla/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }

        stage('Update Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: abhishekf5/cicd-e2e:${BUILD_NUMBER}|g" deploy.yaml
                cat deploy.yaml
                '''
            }
        }

        stage('Push Manifest') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    sh '''
                    git config user.email "jenkins@ci.com"
                    git config user.name "jenkins"

                    git add deploy.yaml
                    git commit -m "Update image tag ${BUILD_NUMBER}"

                    git push https://${GIT_USER}:${GIT_PASS}@github.com/iam-veeramalla/cicd-demo-manifests-repo.git HEAD:main
                    '''
                }
            }
        }
    }
}
